#!/bin/bash

build() {
    add_module "tpm_tis"
    add_module "tpm_crb"
    add_binary "/usr/lib/libtss2-tcti-device.so.0"
    add_binary "/usr/bin/tpm2-totp"
    add_runscript
}

help() {
    cat <<HELPEOF
This hook enabled TPM2 TOTP code verification on boots. Requires a properly setup tpm.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
